var GAME_LEVELS = [
  ["                                                                              ",
   "                                                                              ",
   "                                                                              ",
   "                                                                              ",
   "                                                                              ",
   "                                                                              ",
   "                                                                              ",
   "x                                                                            x",
   "x                                                                            x",
   "x                                                                            x",
   "x  xxxxx xxxxx x     x     xxxxx xxxxx xxxxx  xxxxx xxxxx   x   x   x xxxxx  x",
   "x  x     x   x x     x     x     x       x    x     x   x   x   xx  x x      x",
   "x  x     x   x x     x     xxxxx x       x    x     x   x   x   x x x xxxxx  x",
   "x  x     x   x x     x     x     x       x    x     x   x   x   x  xx     x  x",
   "x  xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx   x    xxxxx xxxxx   x   x   x xxxxx  x",
   "x                                                                            x",
   "x                                                                            x",
   "x   @    o             o                         o                     o     x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                              "],
  ["                                                                                ",
   "                                                                                ",
   "               xxxx                                                             ",
   "                                                                                ",
   "                                                                                ",
   "               foof              xxx   xxx   xxx       xxx                      ",
   "                                              f                                 ",
   "                          o                                                     ",
   "               xxxx       x                                                     ",
   "                              o   f                     f                       ",
   "                              x                                   ooo           ",
   "                                                                  xxx           ",
   "                                  o    ofo    o                 xxx!xxx         ",
   "                                 xxx   xxx   xxx       xxx    xxxx!!!xxxx       ",
   "                                                                xxx!xxx         ",
   "  xx         xxxx                                                 xvx           ",
   "  x          f                  x                                           xxxx",
   "  x                                                     o               o    x  ",
   "  x                                                                    xx    x  ",
   "  x                             f                                            x  ",
   "  x    o                                                                     x  ",
   "  x  @        oof             o   o                              xxxxx       x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                   ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x           x                                                    xx",
   "x!!         x        x                                           xx",
   "xxxv   ooo  x                                                    xx",
   "x     xxxxx x                                                    xx",
   "x     x x!x x        f                                           xx",
   "x    ox  v  x                                                    xx",
   "x    xx    ox                                                    xx",
   "x     x    xx        o                                           xx",
   "x     x     x        x                                           xx",
   "xo    x     x                o                                   xx",
   "xx    xo    x                x                                   xx",
   "x     xx    x                        o                           xx",
   "x     x     x                        x                          oxx",
   "x    ox     x                                 o       o         xxx",
   "x    xx    ox                                xxx     xxx         xx",
   "x     x    xx                                x!x     x!x         xx",
   "x     x     x                                 v       v          xx",
   "xo    x     x                                                    xx",
   "xx    xo    x                                                  xxxx",
   "x     xx    x                                                  xxxx",
   "x     x     x                                                  xxx ",
   "x    ox     x                                                xxxx  ",
   "x    xx    ox                             o       o        xxx     ",
   "xo    x    xx         xxxxxx  xxxxxx     xxx     xxx     xxx       ",
   "x     x               x=    oo     x                               ",
   "x     xo              x     oo    =x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xx @  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["xxxxxxxxxxxxxxxxx                                                                                             ",
   "x               x                                                                                             ",
   "x@              x                                                                                             ",
   "xx              x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                             ",
   "x               x                                                                                            o",
   "x               x                                                                                          xxx",
   "x               x                                                                                  x          ",
   "x               x                                                                  x       x       x          ",
   "x               x                                                          x       x       x       x          ",
   "x               x                                  x       x       x       x       x       x       x          ",
   "x               x                          x       x       x       x       x       x       x       x          ",
   "x                            o      x      x       x       x       x       x       x       x       x          ",
   "x                            x  =   x=    =x   =   x=    = x  =    x    =  x =    =x   =   x=    = x  =    =  ",
   "x     o                      x=   = x  =   x=    = x  =    x    =  x =    =x   =   x=    = x  =    x    =    =",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                               ",
   "                                               ",
   "                                               ",
   "                                               ",
   "                                               ",
   "                                               ",
   " o   o ooooo o   o  o   o   o ooooo o   o o    ",
   " o   o o   o o   o  o   o   o o   o oo  o o    ",
   "  o o  o   o o   o   o o o o  o   o o o o o    ",
   "   o   o   o o   o   o o o o  o   o o  oo      ",
   "   o   ooooo ooooo    o   o   ooooo o   o o    ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                               ",
   " @                                             ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                               ",
   "                                               ",
   "                                               "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
